//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 rewanthtammana.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImmutableKind) DeepCopyInto(out *ImmutableKind) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImmutableKind.
func (in *ImmutableKind) DeepCopy() *ImmutableKind {
	if in == nil {
		return nil
	}
	out := new(ImmutableKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImmutableKind) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImmutableKindList) DeepCopyInto(out *ImmutableKindList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ImmutableKind, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImmutableKindList.
func (in *ImmutableKindList) DeepCopy() *ImmutableKindList {
	if in == nil {
		return nil
	}
	out := new(ImmutableKindList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImmutableKindList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImmutableKindSpec) DeepCopyInto(out *ImmutableKindSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImmutableKindSpec.
func (in *ImmutableKindSpec) DeepCopy() *ImmutableKindSpec {
	if in == nil {
		return nil
	}
	out := new(ImmutableKindSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImmutableKindStatus) DeepCopyInto(out *ImmutableKindStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImmutableKindStatus.
func (in *ImmutableKindStatus) DeepCopy() *ImmutableKindStatus {
	if in == nil {
		return nil
	}
	out := new(ImmutableKindStatus)
	in.DeepCopyInto(out)
	return out
}
